[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "green_hill_cockpit"
version = "0.0.1"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["ghc_dt"]
